inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**'

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 40

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false