# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Add 2 fixed categories
Category.create(name: 'General Discussions')
Category.create(name: 'Staff Announcements')

# Add members of staff from King's NMS
StaffList.create(email: 'luc.moreau@kcl.ac.uk')
StaffList.create(email: 'hamid.aghvami@kcl.ac.uk')
StaffList.create(email: 'asad.ali@kcl.ac.uk')
StaffList.create(email: 'jamie.barras@kcl.ac.uk')
StaffList.create(email: 'elizabeth.black@kcl.ac.uk')
StaffList.create(email: 'rita.borgo@kcl.ac.uk')
StaffList.create(email: 'hana.chockler@kcl.ac.uk')
StaffList.create(email: 'amanda.coles@kcl.ac.uk')
StaffList.create(email: 'andrew.coles@kcl.ac.uk')
StaffList.create(email: 'colin.cooper@kcl.ac.uk')
StaffList.create(email: 'natalia.criado@kcl.ac.uk')
StaffList.create(email: 'vasa.curcin@kcl.ac.uk')
StaffList.create(email: 'zoran.cvetkovic@kcl.ac.uk')
StaffList.create(email: 'yansha.deng@kcl.ac.uk')
StaffList.create(email: 'jian.dai@kcl.ac.uk')
StaffList.create(email: 'mischa.dohler@kcl.ac.uk')
StaffList.create(email: 'stefan.edelkamp@kcl.ac.uk')
StaffList.create(email: 'maribel.fernandez@kcl.ac.uk')
StaffList.create(email: 'maria.fox@kcl.ac.uk')
StaffList.create(email: 'vasilis.friderikos@kcl.ac.uk')
StaffList.create(email: 'christopher.hampson@kcl.ac.uk')
StaffList.create(email: 'matthew.j.howard@kcl.ac.uk')
StaffList.create(email: 'c.iliopoulos@kcl.ac.uk')
StaffList.create(email: 'ernest.kamavuako@kcl.ac.uk')
StaffList.create(email: 'jeroen.keppens@kcl.ac.uk')
StaffList.create(email: 'michael.kolling@kcl.ac.uk')
StaffList.create(email: 'panagiotis.kosmas@kcl.ac.uk')
StaffList.create(email: 'agi.kurucz@kcl.ac.uk')
StaffList.create(email: 'hak-keung.lam@kcl.ac.uk')
StaffList.create(email: 'kevin.lano@kcl.ac.uk')
StaffList.create(email: 'hongbin.liu@kcl.ac.uk')
StaffList.create(email: 'derek.long@kcl.ac.uk')
StaffList.create(email: 'grigorios.loukides@kcl.ac.uk')
StaffList.create(email: 'michael.luck@kcl.ac.uk')
StaffList.create(email: 'daniele.magazzeni@kcl.ac.uk')
StaffList.create(email: 'toktam.mahmoodi@kcl.ac.uk')
StaffList.create(email: 'peter.mcburney@kcl.ac.uk')
StaffList.create(email: 'simon.miles@kcl.ac.uk')
StaffList.create(email: 'sanjay.modgil@kcl.ac.uk')
StaffList.create(email: 'josh.l.murphy@kcl.ac.uk')
StaffList.create(email: 'reza.nakhai@kcl.ac.uk')
StaffList.create(email: 'richard.overill@kcl.ac.uk')
StaffList.create(email: 'simon.parsons@kcl.ac.uk')
StaffList.create(email: 'steve.phelps@kcl.ac.uk')
StaffList.create(email: 'solon.pissis@kcl.ac.uk')
StaffList.create(email: 'maria.polukarov@kcl.ac.uk')
StaffList.create(email: 'jeffery.raphael@kcl.ac.uk')
StaffList.create(email: 'tomasz.radzik@kcl.ac.uk')
StaffList.create(email: 'odinaldo.rodrigues@kcl.ac.uk')
StaffList.create(email: 'isabel.k.sassoon@kcl.ac.uk')
StaffList.create(email: 'nishanth.sastry@kcl.ac.uk')
StaffList.create(email: 'm.sbahaei@kcl.ac.uk')
StaffList.create(email: 'osvaldo.simeone@kcl.ac.uk')
StaffList.create(email: 'elizabeth.sklar@kcl.ac.uk')
StaffList.create(email: 'michael.spratling@kcl.ac.uk')
StaffList.create(email: 'kathleen.steinhofel@kcl.ac.uk')
StaffList.create(email: 'jose.such@kcl.ac.uk')
StaffList.create(email: 'laurence.tratt@kcl.ac.uk')
StaffList.create(email: 'sophia.tsoka@kcl.ac.uk')
StaffList.create(email: 'christian.urban@kcl.ac.uk')
StaffList.create(email: 'luca.vigano@kcl.ac.uk')
StaffList.create(email: 'steffen.zschaler@kcl.ac.uk')